SRC += lzma.c
INITRAMFS_FILES = build/linux-5.1.3/drivers/i2c/busses/i2c-i801.ko

include $(ML_ROOT)/make/app.mk
include $(ML_ROOT)/make/packages/curl-7.65.0.mk
include $(ML_ROOT)/make/packages/heatshrink-0.4.1.mk
include $(ML_ROOT)/make/packages/xz-5.2.4.mk
include $(ML_ROOT)/make/packages/detools-0.29.0.mk
include $(ML_ROOT)/make/packages/openssl-1.1.1b.mk
include $(ML_ROOT)/make/packages/zlib-1.2.11.mk
