SRC += lzma.c

include $(ML_ROOT)/make/app.mk
include $(ML_ROOT)/make/packages/curl-7.65.0.mk
include $(ML_ROOT)/make/packages/heatshrink-0.4.1.mk
include $(ML_ROOT)/make/packages/xz-5.2.4.mk
include $(ML_ROOT)/make/packages/detools-0.29.0.mk
